"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY_INSEGURA_DEV = 'django-insecure-1%(52t9jfpsf!0$k(yb3f_$p-*sk*oc6!s5y6c0-xaab#6h2@l'
SECRET_KEY = env("DJANGO_SECRET_KEY", default=_SECRET_KEY_INSEGURA_DEV)
if not DEBUG and SECRET_KEY == _SECRET_KEY_INSEGURA_DEV:
    # Sin esto, un despliegue con DEBUG=False pero sin DJANGO_SECRET_KEY en el .env
    # arrancaba igual con esta clave de desarrollo — está en el repo, es la misma
    # para cualquiera que lo clone. Mejor fallar fuerte acá que servir tráfico real
    # con una clave que cualquiera con acceso al código ya conoce.
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY no está definida en el entorno: es obligatoria cuando "
        "DJANGO_DEBUG=False (producción)."
    )

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',
    'asistencia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='sc_pne'),
        'USER': env('DB_USER', default='sc_pne'),
        'PASSWORD': env('DB_PASSWORD', default='sc_pne_local'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5434'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Fotos: disco local por defecto (dev y hasta que 20k fotos justifiquen otra cosa).
# Con USE_S3=True en .env, pasa a object storage S3-compatible (DigitalOcean Spaces o
# Hetzner, ya decidido en docs/00-REFERENCIA-PROYECTO.md) sin tocar código — solo
# variables de entorno. Sin credenciales todavía no hay bucket que probar esto.
USE_S3 = env.bool('USE_S3', default=False)
if USE_S3:
    INSTALLED_APPS.append('storages')
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL')  # ej. https://nyc3.digitaloceanspaces.com
    AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default=None)  # CDN, si aplica
    # Privado, NO public-read: las fotos son datos biométricos de postulantes a la
    # Policía Nacional (retención todavía sin definir legalmente por el cliente, ver
    # docs/00-REFERENCIA-PROYECTO.md) — no deben quedar accesibles por URL directa sin
    # autenticar. AWS_QUERYSTRING_AUTH genera URLs firmadas con expiración en vez de
    # públicas permanentes (default de django-storages, explícito acá a propósito).
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = env.int('AWS_QUERYSTRING_EXPIRE', default=3600)
    AWS_S3_FILE_OVERWRITE = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Angular corre en otro puerto (dev) / dominio (prod) — necesita CORS y JWT en vez de
# la sesión de Django (que sería un dolor de cabeza de CSRF cross-origin).
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:4200"]
)

# Umbrales de calidad de encuadre para la foto de registro (ver asistencia/facial.py).
# Están "ajustados a ojo" (ver docs/00-REFERENCIA-PROYECTO.md) — quedan en env para
# poder recalibrarlos con fotos reales sin tocar código ni redeployar, apenas haya
# datos de rechazo/aceptación reales que lo justifiquen.
ASISTENCIA_UMBRAL_SCORE_REGISTRO = env.float("ASISTENCIA_UMBRAL_SCORE_REGISTRO", default=0.9)
ASISTENCIA_PROPORCION_MIN_ROSTRO = env.float("ASISTENCIA_PROPORCION_MIN_ROSTRO", default=0.20)
ASISTENCIA_MARGEN_CENTRADO = env.float("ASISTENCIA_MARGEN_CENTRADO", default=0.20)
ASISTENCIA_TOLERANCIA_ROLL = env.float("ASISTENCIA_TOLERANCIA_ROLL", default=0.35)
ASISTENCIA_RANGO_YAW_MIN = env.float("ASISTENCIA_RANGO_YAW_MIN", default=0.32)
ASISTENCIA_RANGO_YAW_MAX = env.float("ASISTENCIA_RANGO_YAW_MAX", default=0.68)
ASISTENCIA_UMBRAL_BRILLO_MINIMO = env.float("ASISTENCIA_UMBRAL_BRILLO_MINIMO", default=60)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # Con miles de postulantes, /api/asistencias/ sin paginar crece sin límite y el
    # dashboard lo pide entero cada pocos segundos — esto es lo mínimo, no un filtro.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # anon/user son el piso global (cubren registro y el sondeo de encuadre, que
    # polea cada ~900ms mientras el postulante se acomoda — 120/min les da margen
    # cómodo). login/verificar son más estrictos a propósito: fuerza bruta de
    # contraseña y "pesca" de coincidencias 1:N (VerificarAsistenciaView expone
    # datos del postulante en la respuesta) son los dos vectores de abuso reales,
    # sin relación con el volumen normal de uso de un kiosco supervisado.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/min',
        'user': '300/min',
        'login': '10/min',
        'verificar': '30/min',
    },
}
