"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# default False: si el .env de producción olvida esta variable, que falle cerrado
# (y el guard de SECRET_KEY de abajo lo detecta) en vez de servir tracebacks.
DEBUG = env.bool("DJANGO_DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# Sin clave en el repo: la que había versionada firmaba los JWT y las URLs de
# fotos de cualquier dev server (runserver en 0.0.0.0) y se podían forjar.
SECRET_KEY = env("DJANGO_SECRET_KEY", default="")
if not SECRET_KEY and DEBUG:
    # ponytail: aleatoria por proceso — en dev las sesiones/JWT mueren al
    # reiniciar; fijar DJANGO_SECRET_KEY en backend/.env si molesta.
    from django.core.management.utils import get_random_secret_key

    SECRET_KEY = get_random_secret_key()
if not DEBUG and len(SECRET_KEY) < 50:
    # Falla cerrado: sin clave, o con un placeholder tipo "change-me".
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY debe tener al menos 50 caracteres cuando "
        "DJANGO_DEBUG=False (producción)."
    )

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS", default=[])

# Cabeceras/cookies seguras cuando corre detrás de nginx (ver
# docs/DESPLIEGUE-PRODUCCION.md). En DEBUG=True (dev) los defaults no
# cambian nada de lo que ya funciona hoy.
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])
# False hasta que exista un certificado real y se active el bloque HTTPS de
# frontend/nginx.conf -- activarlo antes tumbaría el sitio (redirige a un
# HTTPS que todavía no existe).
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
# TLS termina en nginx: sin esto request.is_secure() es siempre False detrás del
# proxy y SECURE_SSL_REDIRECT=True entra en loop de redirecciones. nginx pisa
# X-Forwarded-Proto con $scheme, así que el cliente no lo puede falsificar.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# 0 hasta tener TLS estable; después 31536000 (un año). Sin HSTS, un atacante en
# la red puede degradar a HTTP la primera visita.
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',
    'asistencia',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # DIRS se busca ANTES que las plantillas de cada app (APP_DIRS) — sin esto,
        # templates/admin/base_site.html (para el tema navy/dorado del admin) nunca
        # ganaría contra la propia admin/base_site.html de django.contrib.admin, que
        # aparece antes en INSTALLED_APPS.
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME', default='sc_pne'),
        'USER': env('DB_USER', default='sc_pne'),
        'PASSWORD': env('DB_PASSWORD', default='sc_pne_local'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5434'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Manifest con hash de contenido + gzip, servido por whitenoise sin nginx
# aparte. Solo en producción: en dev (DEBUG=True) collectstatic ni se corre,
# así que dejar el storage default ahí evita un manifest a medio generar.
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Fotos: disco local por defecto (dev y hasta que 20k fotos justifiquen otra cosa).
# Con USE_S3=True en .env, pasa a object storage S3-compatible (DigitalOcean Spaces o
# Hetzner, ya decidido en docs/00-REFERENCIA-PROYECTO.md) sin tocar código — solo
# variables de entorno. Sin credenciales todavía no hay bucket que probar esto.
USE_S3 = env.bool('USE_S3', default=False)
if USE_S3:
    INSTALLED_APPS.append('storages')
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = env('AWS_S3_ENDPOINT_URL')  # ej. https://nyc3.digitaloceanspaces.com
    AWS_S3_CUSTOM_DOMAIN = env('AWS_S3_CUSTOM_DOMAIN', default=None)  # CDN, si aplica
    # Privado, NO public-read: las fotos son datos biométricos de postulantes a la
    # Policía Nacional (retención todavía sin definir legalmente por el cliente, ver
    # docs/00-REFERENCIA-PROYECTO.md) — no deben quedar accesibles por URL directa sin
    # autenticar. AWS_QUERYSTRING_AUTH genera URLs firmadas con expiración en vez de
    # públicas permanentes (default de django-storages, explícito acá a propósito).
    AWS_DEFAULT_ACL = 'private'
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = env.int('AWS_QUERYSTRING_EXPIRE', default=3600)
    AWS_S3_FILE_OVERWRITE = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Cache compartido en el mismo Postgres: los throttles de DRF (login, códigos,
# registro) viven acá. Con el LocMem por defecto cada worker de gunicorn
# contaba por su lado y los límites reales eran 3x los configurados.
# ponytail: una query por request limitada; Redis solo si se vuelve un cuello.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "cache_django",
    }
}

# Angular corre en otro puerto (dev) / dominio (prod) — necesita CORS y JWT en vez de
# la sesión de Django (que sería un dolor de cabeza de CSRF cross-origin).
CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS", default=["http://localhost:4200"]
)

# Umbrales de calidad de encuadre para la foto de registro (ver asistencia/facial.py).
# Están "ajustados a ojo" (ver docs/00-REFERENCIA-PROYECTO.md) — quedan en env para
# poder recalibrarlos con fotos reales sin tocar código ni redeployar, apenas haya
# datos de rechazo/aceptación reales que lo justifiquen.
ASISTENCIA_UMBRAL_SCORE_REGISTRO = env.float("ASISTENCIA_UMBRAL_SCORE_REGISTRO", default=0.9)
ASISTENCIA_PROPORCION_MIN_ROSTRO = env.float("ASISTENCIA_PROPORCION_MIN_ROSTRO", default=0.20)
ASISTENCIA_MARGEN_CENTRADO = env.float("ASISTENCIA_MARGEN_CENTRADO", default=0.20)
ASISTENCIA_TOLERANCIA_ROLL = env.float("ASISTENCIA_TOLERANCIA_ROLL", default=0.35)
ASISTENCIA_RANGO_YAW_MIN = env.float("ASISTENCIA_RANGO_YAW_MIN", default=0.32)
ASISTENCIA_RANGO_YAW_MAX = env.float("ASISTENCIA_RANGO_YAW_MAX", default=0.68)
ASISTENCIA_UMBRAL_BRILLO_MINIMO = env.float("ASISTENCIA_UMBRAL_BRILLO_MINIMO", default=60)

# Código de verificación de correo en el registro (ver VerificarCorreoView):
# backend de consola en dev (el código se imprime en la terminal del backend,
# nada de correos reales) — SMTP configurable por env para cuando la Policía
# Nacional defina su proveedor real, mismo patrón que USE_S3 arriba.
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='no-reply@localhost')

# El kiosco de verificación ahora exige login de agente (ver VerificarAsistenciaView)
# y el frontend no renueva el token solo: 5 min (default) cortaría el kiosco a mitad
# de la fila. ponytail: una jornada; refresh automático en el interceptor si se acorta.
# CHECK_REVOKE_TOKEN: el token lleva un hash de la contraseña y deja de valer al
# cambiarla (reset de cuenta comprometida). Sin esto un token robado seguía sirviendo.
SIMPLE_JWT = {"ACCESS_TOKEN_LIFETIME": timedelta(hours=8), "CHECK_REVOKE_TOKEN": True}

REST_FRAMEWORK = {
    # Sin esto DRF usa el X-Forwarded-For ENTERO como identidad del throttle, y el
    # cliente lo controla: un valor falso por request evadía todos los límites.
    # 0 = usar la IP real del socket (dev, sin proxy); en producción detrás de
    # nginx va NUM_PROXIES=1 (toma la IP que agregó nginx, la última del XFF).
    'NUM_PROXIES': env.int('NUM_PROXIES', default=0),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # Con miles de postulantes, /api/asistencias/ sin paginar crece sin límite y el
    # dashboard lo pide entero cada pocos segundos — esto es lo mínimo, no un filtro.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    # anon/user son el piso global (cubren registro y el sondeo de encuadre, que
    # polea cada ~900ms mientras el postulante se acomoda — 120/min les da margen
    # cómodo). login/verificar son más estrictos a propósito: fuerza bruta de
    # contraseña y "pesca" de coincidencias 1:N (VerificarAsistenciaView expone
    # datos del postulante en la respuesta) son los dos vectores de abuso reales,
    # sin relación con el volumen normal de uso de un kiosco supervisado.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '120/min',
        'user': '300/min',
        'login': '10/min',
        # OJO: el throttle es POR IP, y todos los puestos de una misma sede salen
        # por la misma IP pública (NAT). Medido el 2026-09-28: con 30/min, la
        # verificación 31 del minuto ya devuelve 429 — o sea que dos puestos
        # trabajando normal empiezan a rebotar postulantes legítimos, que tras 3
        # intentos fallidos caen al override manual y saturan a los agentes.
        # 300/min soporta ~10 puestos a 4 personas/min con 3 intentos cada una;
        # para "pescar" identidades en el 1:N igual harían falta horas de
        # martilleo con miles de fotos de rostros distintos.
        'verificar': '300/min',
        # El sondeo de encuadre polea cada ~900ms mientras la persona se acomoda
        # (66/min por puesto de registro): con el piso anon de 120/min, dos
        # puestos ya lo agotaban y la auto-captura dejaba de funcionar en
        # silencio (camera-capture.ts ignora los errores del sondeo). No guarda
        # nada ni expone datos: puede ser generoso.
        'encuadre': '600/min',
        # Código de 6 dígitos: sin esto, fuerza bruta contra 1M combinaciones es
        # viable. reenviar-codigo más estricto todavía — también evita usarlo de
        # spam de correo hacia un tercero (solo hace falta la cédula).
        'verificar-correo': '10/min',
        'reenviar-codigo': '5/min',
        'solicitar-recuperacion': '10/min',
        'restablecer-password': '5/min',
    },
}
