# Generated by Django 4.2.30 on 2026-09-04 02:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('estatura_cm', models.PositiveSmallIntegerField()),
                ('foto', models.ImageField(upload_to='postulantes/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=512)),
                ('sede', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=100)),
                ('verificado_en', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('AUTO', 'Automático (reconocimiento facial)'), ('MANUAL', 'Manual (forzado por agente)')], default='AUTO', max_length=10)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('forzado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asistencias_forzadas', to=settings.AUTH_USER_MODEL)),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='asistencia.postulante')),
            ],
        ),
    ]
