# Generated by Django 4.2.30 on 2026-09-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_postulante_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='verificado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
