# Generated by Django 4.2.30 on 2026-09-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_alter_asistencia_verificado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='postulantes/'),
        ),
    ]
