# Generated by Django 4.2.30 on 2026-09-13 18:11

import asistencia.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_alter_postulante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('OTRO', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, validators=[asistencia.validators.validar_cedula_ecuatoriana]),
        ),
        migrations.CreateModel(
            name='FotoPostulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='postulantes/adicionales/')),
                ('embedding', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=128)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionales', to='asistencia.postulante')),
            ],
        ),
    ]
