# Generated by Django 4.2.30 on 2026-09-13 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistencia', '0005_postulante_correo_postulante_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postulante', to=settings.AUTH_USER_MODEL),
        ),
    ]
