# Generated by Django 4.2.30 on 2026-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_postulante_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
