# Generated by Django 4.2.30 on 2026-09-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0007_alter_postulante_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='codigo_generado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
