# Generated by Django 4.2.30 on 2026-09-30 01:43

import asistencia.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0008_postulante_codigo_generado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='cedula',
            field=models.CharField(error_messages={'unique': 'Ya existe un postulante con esta cédula.'}, max_length=10, unique=True, validators=[asistencia.validators.validar_cedula_ecuatoriana]),
        ),
    ]
