# Generated by Django 4.2.30 on 2026-09-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0009_alter_postulante_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='correo',
            field=models.EmailField(blank=True, error_messages={'unique': 'Ya existe un postulante con este correo.'}, max_length=254, null=True, unique=True),
        ),
    ]
