# Generated by Django 4.2.30 on 2026-10-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0010_alter_postulante_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='intentos_codigo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
