# Generated by Django 4.2.30 on 2026-10-01 18:19

from django.db import migrations, models


def marcar_cuentas_activas(apps, schema_editor):
    # Una cuenta activa hoy ya pasó por verificar-correo (el registro la crea
    # inactiva): sin esto quedarían todas como "pendientes" y un admin que las
    # deshabilite podría ver cómo se reactivan solas.
    Postulante = apps.get_model("asistencia", "Postulante")
    Postulante.objects.filter(usuario__is_active=True).update(correo_verificado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0011_intentos_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='correo_verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(marcar_cuentas_activas, migrations.RunPython.noop),
    ]
