# Generated by Django 4.2.30 on 2026-10-02 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0012_correo_verificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoRepetido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=100)),
                ('intentado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_repetidos', to='asistencia.postulante')),
            ],
        ),
    ]
